### ISSUE TITLE
R code reorg

### ISSUE THREAD

**Issue by disa-mhembere** [youngser/D3M#1]
From a software dev position I've done something unmaintainable by producing redundant `R` code in the `python` wrapper. I would like to suggest the following reorg:

* separate each `R` script  into 2 files:
  1.  An interface script with an uncalled function
  2. A command line callable script that is a user facing script

I've done this for `oocase` -- see [SRC](https://github.com/youngser/D3M/tree/python/oocase/SRC). It leads to very simple, short and most importantly *maintainable* wrappers see [python](https://github.com/youngser/D3M/blob/python/oocase/python/oocase.py#L28)

Thoughts?

**Comment by youngser** [comment]
Agreed! I will try to do that for the rest of the primitives and the three other ones.

BTW, is this related to what we talked about on the board yesterday?
This is nothing to do with the TA2 API Interface, which we won't know until it's finalized, right?

**Comment by disa-mhembere** [comment]
Nope it is unrelated to TA2, but will just help to keep everything
maintainable :)

On Sep 12, 2017 10:09 AM, "youngser" <notifications@github.com> wrote:

Agreed! I will try to do that for the rest of the primitives and the three
other ones.

BTW, is this related to what we talked about on the board yesterday?
This is nothing to do with the TA2 API Interface, which we won't know until
it's finalized, right?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/youngser/D3M/issues/1#issuecomment-328861347>, or mute
the thread
