### ISSUE TITLE
Consistent paths

### ISSUE THREAD

**Issue by disa-mhembere** [youngser/D3M#2]
* Let's standardize paths:
    - Some places we use "~/path/to/file", others use
      "/home/user/D3M/DATA/eigenvalues.txt". Perhaps we should unify so it
      either always works or it doesn't?

Thoughts?

**Comment by youngser** [comment]
The latter is the path *inside* the docker. 
Because all the primitives live in "./SRC" and the data in "./DATA", and we call the primitives via "Rscript *.R" and/or "python .py", let's use the output "../DATA/*.txt" !?

**Comment by disa-mhembere** [comment]
Yes I agree! Well as long as we guarantee `../DATA` **always** exists of course :)

**Comment by youngser** [comment]
Yep, I thought about it.
Maybe I add `dir.create("../DATA")` first...

**Comment by disa-mhembere** [comment]
yes, this should work as long as the user has permission to write this directory which I guess is ok to assume
