### ISSUE TITLE
Python/ry2 incompatibility

### ISSUE THREAD

**Issue by youngser** [youngser/D3M#3]
I tried to install ry2 on my mac as well as linux docker image, both running python 2.7, and experienced an issue.

@DSP137, I remember you were running python 3, and do you remember how you solved this?
@disa-mhembere, note that this will be an issue with docker...

**Comment by disa-mhembere** [comment]
she solved it by using `pip3 install rpy2`

Can you try `pip install rpy2==2.8.0`. Or check which was the the last version that worked for 2.7 [here](https://pypi.org/project/rpy2/#history)

**Comment by youngser** [comment]
Ok, Thank!
It looks like pip3 is for python3, so I just upgrade it.
Now, it seems working!
Thanks!!
