### ISSUE TITLE
sgm & vnsgm

### ISSUE THREAD

**Issue by youngser** [youngser/D3M#5]
From @DSP137:

> The functions `sgm` and `vnsgm` do not yet run with the python wrapper. @disa-mhembere  said he thinks he knows what's going on with the `sgm` wrapper and will look into it. The test function does not work for `vnsgm`. ~~The data sets in the vnsgm folder are not graph objects~~. I also tried to use the data sets from the `sgm` folder which are .gml files, to no avail.

**Comment by youngser** [comment]
I see that most of the wrappers have lines `source(*.interface.R)`.
The JPL guy said that this won't work, because all they will have/take is a python file!

So, my (and the JPL guy's) questions are

1. Can we modify the wrappers so that they don't have `source` lines? I remember that's what we have earlier?

2. Is it possible to have all the wrappers as a single python package == pip installable ??

**Comment by youngser** [comment]
For #1, will it be better if I include all the `*.interface.R` files inside a new R package I'm writing (let's call it `JHUD3M` ?? Then, I think it minimizes the revision of the wrappers? No?

**Comment by disa-mhembere** [comment]
I use full paths like this: [line 30](https://github.com/youngser/D3M/blob/api/ase/SRC/ase.py#L30). How won't this work when it is it populated based upon the location of the calling file see [line 27](https://github.com/youngser/D3M/blob/api/ase/SRC/ase.py#L27) ?
