### ISSUE TITLE
Unknown Argument types

### ISSUE THREAD

**Issue by disa-mhembere** [youngser/D3M#6]
I notice there are some functions that do not expect graphs, can we document what the arguments are:
- `nonpar.interface <- function(input1, input2, sigma=0.5)`
- `gclust.interface <- function(input, K=2)`
- `numclust.interface <- function(input)`

**Comment by youngser** [comment]
* nonpar.interface <- function(input1, input2, sigma=0.5): 
- input1, input2: output from ase/lse.
- sigma: a bandwidth for the Gaussian kernel

* gclust.interface <- function(input, K=2):
- input: output from ase/lse,
- K: maximum number of clusters.

* numclust.interface <- function(input):
- input: output criteria from clustering algorithm, e.g., BIC, ASW, etc...

**Comment by disa-mhembere** [comment]
Sorry I should have been more specific.

I need data types like "dcGMatrix" or "list"? I need to wrap the R type with a Python type so I can pass it without conversion (hopefully). 

Also these are all primitives that are of type `Transform` right?
