### ISSUE TITLE
accidental commit?

### ISSUE THREAD

**Issue by disa-mhembere** [youngser/D3M#7]
I guess something went wrong and you weren't trying to do this to [`ase.interface.R`](https://github.com/youngser/D3M/blob/master/ase/SRC/ase.interface.R)? 

Can you show me what you expect this to look like?

**Comment by youngser** [comment]
Oh, I thought I deleted the second `return`...
It should be

```
    X <- embed_adjacency_matrix(g, dim)$X
    return(X)
```

**Comment by disa-mhembere** [comment]
yup you fixed it

**Comment by youngser** [comment]
There was an (similar) error in `lse.interface.R`. I fixed it so change `api` accordingly.
