### ISSUE TITLE
vnsgm.interface.R bug

### ISSUE THREAD

**Issue by disa-mhembere** [youngser/D3M#8]
So `sgm` works, but there is a bug in R code. `x` is not defined [here](https://github.com/youngser/D3M/blob/api/vnsgm/SRC/vnsgm.interface.R#L26). Can someone fix this and push it to their branch (i.e., Youngser to `master` or Heather to `dsp`)?

Thanks!

**Comment by youngser** [comment]
It's fixed; `voi` == `x`.

**Comment by disa-mhembere** [comment]
Ok aand what is the type and description of what `voi` is?

**Comment by youngser** [comment]
It can be an integer or a vector of integers.

```
#' @param x vector of indices for vertices of interest (voi) in \eqn{G_1}
```

**Comment by disa-mhembere** [comment]
ok and `s` is?

**Comment by youngser** [comment]
Oh, it's an integer, the number of seeds.

**Comment by disa-mhembere** [comment]
Great, thanks
